**Задача 4. Рост взрослого населения города X имеет нормальное распределение.
Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:**

a) больше 182 см

b) больше 190 см

c) от 166 см до 190 см

d) от 166 см до 182 см

e) от 158 см до 190 см

f) не выше 150 см или не ниже 190 см

g) не выше 150 см или не ниже 198 см

h) ниже 166 см.

**Решение:**\
    Для решения всех примеров будем использовать формулу **Z = (x - m(X)) / σ**, где\
    X - случайная величина, по которой будем искать значение\
    M(X) - математическое ожидание. **M(X) = 174**\
    σ - среднее квадратичное. **σ = 8**
 

In [1]:
def value_Z(x):
    return (x-174)/8

Для расчете значений вероятности можно воспользоваться он-лайн калькулятором: https://gallery.shinyapps.io/dist_calc/ ,\
либо таблицами, либо методом sdf() объекта NormalDist в модуле statistics

a) **больше 182 см**\
Метод cdf возвращает вероятность промежутка до 182, а нам надо выше 182. Поэтому итоговый результат надо вычесть из 1

In [2]:
from statistics import NormalDist as ND
pA = 1 - ND().cdf(value_Z(182))
print(f'P(X>=182) = {pA: .4f}')

P(X>=182) =  0.1587


b) **больше 190см**

In [3]:
pB = 1 - ND().cdf(value_Z(190))
print(f'P(X>=190) = {pB: .4f}')

P(X>=190) =  0.0228


c) **от 166 до 190**\
Найдем сначала значение до 190, а потом вычтем из него значение до 166

In [4]:
pC1 = ND().cdf(value_Z(190))
pC2 = ND().cdf(value_Z(166))
print(f'P(166<=X<=190) = {pC1-pC2: .4f}')

P(166<=X<=190) =  0.8186


d) **от 166 до 182**\
Найдем сначала значение до 182, а потом вычтем из него значение до 166

In [5]:
pD1 = ND().cdf(value_Z(182))
pD2 = ND().cdf(value_Z(166))
print(f'P(166<=X<=182) = {pD1-pD2: .4f}')

P(166<=X<=182) =  0.6827


e) **от 158 до 190**\
Сначала ищем значение до 190, а потом до 158

In [6]:
pE1 = ND().cdf(value_Z(190))
pE2 = ND().cdf(value_Z(158))
print(f'P(158<=X<=190) = {pE1-pE2: .4f}')

P(158<=X<=190) =  0.9545


f) **не выше 150 см или не ниже 190 см**\
В данном примере мы ищем вероятность ниже 150, и вероятность выше 190. А результат складываем

In [7]:
pF1 = ND().cdf(value_Z(150))
pF2 = 1 - ND().cdf(value_Z(190))
print(f'P(X<=158 и X>=190) = {pF1+pF2: .4f}')

P(X<=158 и X>=190) =  0.0241


g) **не выше 150 см или не ниже 198 см**
В данном примере мы ищем вероятность ниже 150, и вероятность выше 198. А результат складываем

In [8]:
pG1 = ND().cdf(value_Z(150))
pG2 = 1 - ND().cdf(value_Z(198))
print(f'P(X<=158 и X>=198) = {pG1+pG2: .4f}')

P(X<=158 и X>=198) =  0.0027


h) **ниже 166**

In [9]:
pH = ND().cdf(value_Z(166))
print(f'P(X<=166) = {pH: .4f}')

P(X<=166) =  0.1587


Ответ:\
a) 0.1587 = 15.8%\
b) 0.0228 = 2.3%\
c) 0.8186 = 81.7%\
d) 0.6827 = 68.3%\
e) 0.9545 = 95.5%\
f) 0.0241 = 5.4%\
g) 0.0027 = 0.3%\
h) 0.1587 = 15.9%